[package]
name = "pipi-server"
version = "26.9.3"
description = "Pipi 的 Web/远程运行时服务"
edition = "2021"

[[bin]]
name = "pipi-server"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
pipi-core = { path = "../pipi-core" }
pipi-app = { path = "../pipi-app" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "macros", "net", "rt-multi-thread", "signal", "sync"] }
tower-http = { version = "0.6", features = ["fs", "cors"] }
tower = "0.5"
